src/articles/urls.py
from django.urls import path
from articles.views import BlogHome

from articles.views import BlogArticleDetail, BlogArticleEdit, BlogArticleDelete

app_name = "articles"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('edit/<str:slug>/', BlogArticleEdit.as_view(), name="edit"),
    path('<str:slug>/', BlogArticleDetail.as_view(), name="article"),
    path('delete/<str:slug>/', BlogArticleDelete.as_view(), name="delete"),
]

src/blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls'), name="homepage"),
]

src/articles/models.py
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField()
    author = models.TextField()
    published = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('blog_post_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_on']

        def __str__(self):
            return self.title

src/articles/views.py
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from articles.models import Article
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.http import HttpResponse


# Create your views here.
class BlogHome(ListView):
    model = Article
    context_object_name = "articles"

    # if admin is logged, we display all articles. Else, we display tje online articles.
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogArticleDetail(DetailView):
    model = Article
    context_object_name = "article"


class BlogArticleEdit(UpdateView):
    model = Article
    template_name = 'articles/article_edit.html'
    fields = ['title', 'content', 'published', ]
    success_url = '/'


class BlogArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:home')

src/templates/articles/article_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

src/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ article.title }}</title>
{% endblock %}

{% block content %}



        <article class="mb-4">
            <div class="container px-1 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-warning">
                            <a href="{% url 'articles:edit' article.slug %}">Editer</a>
                        </button>

                        <button type="button" class="btn btn-danger">
                            <a href="{% url 'articles:delete' article.slug %}">Supprimer</a>
                        </button>
                        {% endif %}
                        <h1 class="text-center">{{article.title}}</h1>
                        <p class="text-right">Ecrit par {{article.author}} le {{article.created_on|date:'j F Y'}}</p>
                        <p class="text-justify">{{article.content}}</p>
                        <a href="{% url 'articles:home' %}" class="btn btn-primary">Retour à l'accueil</a>

                    </div>
                </div>

            </div>
        </article>

{% endblock %}

src/templates/articles/article_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Éditer l'article</title>
{% endblock %}

{% block content %}

    <h1>Éditer l'article</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Éditer">
    </form>

{% endblock %}

src/templates/articles/article_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}
        <div class="container">
        <h1 class="mb-4">Le blog de Docstring</h1>
        {% for article in articles %}
            <div class="card mb-3">
              <div class="card-header">
                Publié le {{article.created_on | date:'j F Y'}} par <i>{{article.author}}</i>
              </div>
              <div class="card-body">
                <h5 class="card-title">{{article.title}}</h5>
                <p class="card-text">{{article.content|safe|truncatewords:50}}</p>
                <a href="{{article.slug}}" class="btn btn-primary">Voir l'article en détail</a>
              </div>
            </div>

        {% endfor %}
        </div>

{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'articles/style.css' %}">
    {% block title %}{% endblock %}
</head>
<body>
<section id="blog">
    {% block content %}{% endblock %}
</section>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>